server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource: 
    password: 4488
    url: jdbc:postgresql://localhost:5432/logisticsDB
    username: postgres
jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  show-sql: true
